### ISSUE TITLE
.SQL File missing needed tables? Or am I just stupid?

### ISSUE THREAD

**Issue by mobbsti** [Scarso327/PhoenixRP-Altis-Mission#1]
Hi,
when setting up a test server, the extDB3 logs show many tables that don't exist in the .sql file provided, this causes me to be infinitely stuck on "Setting up map" when joining the game. I've attached my logs, if you could help that would be great!
[https://pastebin.com/XnFQk10R](url)

Thank you!

**Comment by Scarso327** [comment]
The repo has the wrong SQL file. I'll upload the correct schema shortly. If anyone is reading this and I haven't uploaded it just send me a message on discord and I'll send it then.
