### ISSUE TITLE
Its not connecting to the database

### ISSUE THREAD

**Issue by Jakew125** [Scarso327/PhoenixRP-Altis-Mission#10]
Hello, so I am having a problem where it says it's not connecting to the database, I have tried to use all my knowledge to figure it out, I have even tried to google for a solution but none seems to be working, got any tips on how I may fix it?

**Comment by Scarso327** [comment]
https://github.com/Scarso327/PhoenixRP-Altis-Mission/issues/12
https://github.com/Scarso327/PhoenixRP-Altis-Mission/issues/9

Possibly related issues

@Jakew125
