### ISSUE TITLE
Problem with get into vehicle function which are part of dlc

### ISSUE THREAD

**Issue by Anthony4612** [Scarso327/PhoenixRP-Altis-Mission#13]
Hello, sorry to bother you. I know you have other things to do but if you ever have a few minutes. I need help getting into the DLC vehicles. The function via the Windows menu does not work. Do you know where this can come from?

**Comment by Scarso327** [comment]
https://github.com/Scarso327/PhoenixRP-Altis-Mission/blob/main/PhoenixRP.Altis/PHX/GUI/Interactions/Functions/Buttons/fn_vehicle.sqf

Lines 62 - 66 are the lines you'd be interested in. I can't see anything wrong at a glance.

**Comment by Anthony4612** [comment]
Thanks, I tried several things but nothing worked. I don't understand why it's not working either.

**Comment by Anthony4612** [comment]
Resolved
