### ISSUE TITLE
can you help me script

### ISSUE THREAD

**Issue by darknightsd** [Scarso327/PhoenixRP-Altis-Mission#19]
is there any chance that you can share the unlocked version of the mission?

**Comment by Scarso327** [comment]
I don't understand what you mean - there is nothing "locked" about the mission here?

**Comment by darknightsd** [comment]
the map is invalid when I edit the map 
when the map is edited, the names are not edited, it writes NULL

**Comment by darknightsd** [comment]
![image](https://github.com/Scarso327/PhoenixRP-Altis-Mission/assets/140184706/b89ce781-1cba-4c21-964d-003aca378201)

**Comment by Scarso327** [comment]
Just open the file in arma 3, and it'll open without issue.

**Comment by darknightsd** [comment]
yes, it opens without problems, but I can't edit the names in the file
![image](https://github.com/Scarso327/PhoenixRP-Altis-Mission/assets/140184706/13824579-1c95-41b2-be38-0a8e65a562bd)

**Comment by Scarso327** [comment]
Those can be changed in the editor when you open the map.

**Comment by darknightsd** [comment]
which part can I edit from, can you give me information?

**Comment by Scarso327** [comment]
![image](https://github.com/Scarso327/PhoenixRP-Altis-Mission/assets/11757920/8a3954f2-5d17-486d-9715-bd47376b18e8)

Under the "Attributes" tab then "General"

**Comment by darknightsd** [comment]
thanks, I figured it out, and when buying this car, he wants a donoter, how can I buy without it

**Comment by Scarso327** [comment]
https://github.com/Scarso327/PhoenixRP-Altis-Mission/blob/main/PhoenixRP.Altis/PHX/Configuration/CfgVehicles.hpp

All vehicle stores are configured here. I recommend going through tutorials on https://www.altisliferpg.com/ if you're looking to learn. This mission is based on Tonic's framework so most of what you'll want to do applies.

**Comment by darknightsd** [comment]
![image](https://github.com/Scarso327/PhoenixRP-Altis-Mission/assets/140184706/19545918-1291-4c0c-bdf3-8053aabc3e55)
that's the problem
