### ISSUE TITLE
Loyal fans of PhoenixRP

### ISSUE THREAD

**Issue by xiaohuo9986** [Scarso327/PhoenixRP-Altis-Mission#2]
Dear Jack Farhall
Hello, I am a loyal fan of yours. I also like your PhoenixRP very much. When I learned that it was going to be closed, I felt very disappointed. Therefore, I hope that PhoenixRP will continue to operate in my country. I wonder if I can do this?

**Comment by Scarso327** [comment]
You'd have to discuss the continuation of PHXRP with Kevin really. I share this repo as more of an educational tool than just a straight-up mission to be used.

**Comment by xiaohuo9986** [comment]
How should I contact Kevin to discuss the continuation of PHXRP

**Comment by Scarso327** [comment]
yes
