### ISSUE TITLE
2 Quick Questions

### ISSUE THREAD

**Issue by zSolo** [Scarso327/PhoenixRP-Altis-Mission#3]
1st Thanks for releasing this!

Looking though the files i see you have isCID calls although when someone has cid level (mi5) your unable to use the shops or go undercover, was this removed?

Lastly, dynamic market do the prices actually shift? i see its not the common Market created by Ryan

Thanks!

**Comment by Scarso327** [comment]
The dynamic market was never finished. It was something I lost after a hard drive issue and never got round to finishing again. As for CID, I am fairly certain it was removed and was planned to be implemented at the time of this mission.

**Comment by zSolo** [comment]
Got ya thanks!
