### ISSUE TITLE
init.sqf

### ISSUE THREAD

**Issue by Simon-commit** [Scarso327/PhoenixRP-Altis-Mission#4]
Whenever I try to launch the mission file, I get this message: https://prnt.sc/yjqb2f but when I look in the life_server folder the file is there.

The script seems to be very vital cause later on in the process of loading in I just get stuck at the "Waiting for the server to be ready..." screen

**Comment by Scarso327** [comment]
You need to make sure that @life_sever/addons/life_server.pbo exists on the server side.
