### ISSUE TITLE
Unable Store Vehicles

### ISSUE THREAD

**Issue by zSolo** [Scarso327/PhoenixRP-Altis-Mission#5]
Anyone having issues with the Tuning Shop or Being able to Store brought cars?

When ever i Buy not Rent i get the following  Expression Error:

< DB_fnc_asyncCall; _id = (_id select 0) + 1;
if !(_vehicle isEqualTo "") then {> 2021/02/03, 17:52:51 Error position: <+ 1;
if !(_vehicle isEqualTo "") then {>

Which i think is not creating a entry into the DB

**Comment by Scarso327** [comment]
Hello, this was caused by an oversight with my jank method for getting the id for a newly bought vehicle. I've committed a fix.

https://github.com/Scarso327/PhoenixRP-Altis-Mission/commit/dd4f16dfeae4ba93929efe555c9cd8160af69b81

If you can get back to me and tell me if that helped, please do.

**Comment by zSolo** [comment]
Thanks for seeing this - The fix worked!

Enjoy the rest of your day
