### ISSUE TITLE
Couple Questions please

### ISSUE THREAD

**Issue by SmokeyLion** [Scarso327/PhoenixRP-Altis-Mission#7]
Greetings to you,

My first question is no matter where I look I am unable to find the spot to add admins for the back end stuff (such as an admin on the tablet etc etc.)

Second question is pertaining to unable to locate where to add whitelist UID's for cops etc.

Thanks so much!

**Comment by Scarso327** [comment]
Assuming you've set up a server and got it connected to a database you do this by changing their whitelisting values in the Players table of the database. This is the same for factions and Admin.

**Comment by SmokeyLion** [comment]
I assume I am just missing the table here. Or does Altis Life base SQL need to be merged with the SQL provided? I do not see anywhere on player values for whitelist etc.

**Comment by SmokeyLion** [comment]
Nvm I am dumb lol
